### PR TITLE
feat: HSRPv1

### PR DESCRIPTION
**Pull request by stmosher**
HSRPv1, plus for C9k stop unnecessary and rejected dot1q trunk command, and now raises error when switchport configured under ethernetCSMACD (should be l2vlan)

### CODE REVIEW

**Review by stevenca — DISMISSED** [review]

**Comment by lvangink** [comment]
Approved

**Review by lvangink — DISMISSED** [review]
Approved

**Review by lvangink — APPROVED** [review]
Looks like good code

**Review by lvangink — DISMISSED** [review]
Approved

**Review by jrouliez — APPROVED** [review]

**Review by m0lass3s — DISMISSED** [review]

**Review by jrouliez — DISMISSED** [review]

**Review by m0lass3s — APPROVED** [review]

**Review by m0lass3s — APPROVED** [review]

**Review by m0lass3s — DISMISSED** [review]

**Review by m0lass3s — DISMISSED** [review]

**Review by m0lass3s — APPROVED** [review]

**Pull request closed without merging**
