### PR TITLE
feat: interfaces ipv6 and VRRPv3

### PR DESCRIPTION
**Pull request by stmosher**

### CODE REVIEW

**Review by jasonking3 — APPROVED** [review]

**Review by stevenca — APPROVED** [review]
Re-approving.

**Review by stevenca — APPROVED** [review]
LGTM

**Review by stevenca — APPROVED** [review]
Lot's of files.

**Review by jasonking3 — APPROVED** [review]

**Review by stevenca — APPROVED** [review]
LGTM

**Review by stevenca — APPROVED** [review]
LGTM

**Pull request merged**
